version: '3.8'

services:
  web:
    build: ./src
    container_name: sheet
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app
    command: go run github.com/twelc/go-sheets -b 0.0.0.0
  parser:
    build: ./parser
    container_name: parser
    volumes:
      - ./parser:/usr/src/app
    command: bash -c "service tor start && python ./nb_parser.py"